import type { Metadata } from "next";
import { Lora, Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/ui/Header";

const lora = Lora({
 weight:['400', '500', '600', '700'],
  subsets: ["latin"],
  variable:'--font-lora'
});

const poppins = Poppins({
  subsets: ["latin"],
  variable:'--font-poppins',
  weight:['100', '200', '300', '400', '500', '600', '700', '800', '900'],

 });

export const metadata: Metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${poppins.variable}  `}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
